apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
  labels:
    control-plane: operator
    app.kubernetes.io/name: operator
    app.kubernetes.io/instance: operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: operator
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: operator
      labels:
        control-plane: operator
        app: operator
    spec:
      containers:
      - command:
        - /operator
        args:
        - "--loglevel=debug"
        image: controller:main
        imagePullPolicy: IfNotPresent
        name: operator
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: operator
