resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- secrets_role.yaml
- nodemarker_cluster_role.yaml
- nodemarker_cluster_role_binding.yaml
- nodemarker_role.yaml
- nodemarker_role_binding.yaml
- perouter_role.yaml
- perouter_role_binding.yaml
