---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodemarker-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - openpe-validating-webhook-configuration
  resources:
  - validatingwebhookconfigurations
  verbs:
  - update
- apiGroups:
  - network.openperouter.io
  resources:
  - l2vnis
  - l3passthroughs
  - l3vnis
  - l3vpns
  - rawfrrconfigs
  - underlays
  verbs:
  - get
  - list
  - watch
