---
# L3Passthrough for DMZ nodes
apiVersion: network.openperouter.io/v1alpha1
kind: L3Passthrough
metadata:
  name: dmz-passthrough
  namespace: openperouter-system
spec:
  nodeSelector:
    matchLabels:
      security-zone: dmz
  hostSession:
    asn: 64512
    hostASN: 64710
    localCIDR:
      ipv4: 192.169.21.0/24
---
# L3Passthrough for internal nodes
apiVersion: network.openperouter.io/v1alpha1
kind: L3Passthrough
metadata:
  name: internal-passthrough
  namespace: openperouter-system
spec:
  nodeSelector:
    matchLabels:
      security-zone: internal
  hostSession:
    asn: 64512
    hostASN: 64720
    localCIDR:
      ipv4: 192.169.22.0/24

