apiVersion: network.openperouter.io/v1alpha1
kind: Underlay
metadata:
  name: underlay
  namespace: openperouter-system
spec:
  asn: 64514
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: node-1
  tunnelEndpoint:
    cidrs:
    - 100.65.0.0/24
  interfaces:
    - type: CNIDevice
      cniDevice:
        type: RawConfig
        interfaceName: net1
        rawConfig:
          cniVersion: "1.0.0"
          name: macvlan-underlay
          plugins:
            - type: macvlan
              master: eth0
              mode: bridge
              capabilities:
                mac: true
              ipam:
                type: dhcp
        runtimeConfig:
          mac: "aa:bb:cc:00:00:01"
  neighbors:
    - asn: 64512
      address: 192.168.11.2
