#!/usr/bin/env bash

# SPDX-License-Identifier:Apache-2.0

NETNS=${NETNS:-""}

args=""
if [ -n "$NETNS" ]; then
	args="ip netns exec $NETNS"
fi

readonly NETNS_INFO=(\
"ip link" \
"ip address" \
"ip route" \
"ip neigh" \
"ip vrf" \
"bridge fdb show" \
)

readonly VRF_SHOW="ip -br link show type vrf"
readonly VRF_INFO=(\
"ip link show type vrf"
"ip route show vrf"
"ip address show vrf"
)

function print_vrf_info {
  local -r netns_name=$1
  local -r args="$2"

  vrfs=("$($args $VRF_SHOW | awk '{print $1}')")
  [[ ${#vrfs} -eq 0 ]] && return

  echo "### netns [$netns_name] VRFs:"
  $args $VRF_SHOW

  for vrf in "${vrfs[@]}"; do
    echo "### netns [$netns_name] VRF [$vrf]:"
    for cmd in "${VRF_INFO[@]}"; do
      c="$args $cmd $vrf"
      echo "$ $c"
      $c
    done
  done
  echo "###"
}

echo "### Networking info:"
for cmd in "${NETNS_INFO[@]}"; do
	c="$args $cmd"
	echo "$ $c"
	$c
	echo ""
done
echo "###"
echo ""

if [[ -n $NETNS ]]; then
  print_vrf_info "$NETNS" "$args"
else
  print_vrf_info "root" ""
fi
