apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    {{- include "openperouter.labels" . | nindent 4 }}
    component: controller
    {{- range $key, $value := .Values.openperouter.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: controller
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- if .Values.openperouter.updateStrategy }}
  updateStrategy: {{- toYaml .Values.openperouter.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "openperouter.selectorLabels" . | nindent 6 }}
      component: controller
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: controller
      labels:
        {{- include "openperouter.selectorLabels" . | nindent 8 }}
        component: controller
        app: controller
        {{- range $key, $value := .Values.openperouter.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- if .Values.openperouter.runtimeClassName }}
      runtimeClassName: {{ .Values.openperouter.runtimeClassName }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "openperouter.controller.serviceAccountName" . }}
      containers:
      - args:
        - --nodename=$(NODE_NAME)
        - --namespace=$(NAMESPACE)
        - --frrconfig=/etc/frr/frr.conf
        {{- with .Values.openperouter.logLevel }}
        - --loglevel={{ . }}
        {{- end }}
        {{- if eq .Values.openperouter.cri "containerd" }}
        - --crisocket=/containerd.sock
        {{- end }}
        {{- if eq .Values.openperouter.cri "crio" }}
        - --crisocket=/crio.sock
        {{- end }}
        {{- if .Values.openperouter.multusNetworkAnnotation }}
        - --underlay-from-multus=true
        {{- end }}
        command:
        - /controller
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ .Values.openperouter.image.repository }}:{{ .Values.openperouter.image.tag | default .Chart.AppVersion }}
        {{- if .Values.openperouter.image.pullPolicy }}
        imagePullPolicy: {{ .Values.openperouter.image.pullPolicy }}
        {{- end }}
        name: controller
        {{- with .Values.openperouter.controller.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
            - NET_BIND_SERVICE
          privileged: true
        volumeMounts:
        {{- if eq .Values.openperouter.cri "containerd" }}
        - mountPath: /containerd.sock
          name: varrun
          subPath: containerd.sock
        {{- end }}
        {{- if eq .Values.openperouter.cri "crio" }}
        - mountPath: /crio.sock
          name: varrun
          subPath: crio.sock
        {{- end }}
        - mountPath: /run/netns
          mountPropagation: HostToContainer
          name: runns
        - mountPath: /etc/frr/
          mountPropagation: HostToContainer
          name: frr-config
      hostNetwork: true
      hostPID: true
      tolerations:
      {{- if .Values.openperouter.runOnMaster }}
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      {{- end }}
      {{- with .Values.openperouter.tolerations }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.openperouter.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      volumes:
      - hostPath:
          path: /run/netns
        name: runns
      {{- if eq .Values.openperouter.cri "containerd" }}
      - hostPath:
          path: /run/containerd
        name: varrun
      {{- end }}
      {{- if eq .Values.openperouter.cri "crio" }}
      - hostPath:
          path: /var/run/crio
        name: varrun
      {{- end }}
      - hostPath:
          path: /etc/perouter/frr
          type: DirectoryOrCreate
        name: frr-config
