{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "openperouter.labels" . | nindent 4 }}
    component: nodemarker
    {{- range $key, $value := .Values.openperouter.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: openpe-webhook-server-cert 
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "openperouter.labels" . | nindent 4 }}
    component: nodemarker
    {{- range $key, $value := .Values.openperouter.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: openpe-webhook-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - port: 443
      targetPort: webhook-server
  selector:
    component: nodemarker
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    {{- include "openperouter.labels" . | nindent 4 }}
    component: nodemarker
    {{- range $key, $value := .Values.openperouter.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: openpe-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: openpe-webhook-service
      namespace: {{ .Release.Namespace | quote }}
      path: /validate-openperouter-io-v1alpha1-l2vni
  failurePolicy: Fail
  name: l2vnivalidationwebhook.openperouter.io
  rules:
  - apiGroups:
    - openpe.openperouter.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - l2vnis
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: openpe-webhook-service
      namespace: {{ .Release.Namespace | quote }}
      path: /validate-openperouter-io-v1alpha1-l3vni
  failurePolicy: Fail
  name: l3vnivalidationwebhook.openperouter.io
  rules:
  - apiGroups:
    - openpe.openperouter.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - l3vnis
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: openpe-webhook-service
      namespace: {{ .Release.Namespace | quote }}
      path: /validate-openperouter-io-v1alpha1-underlay
  failurePolicy: Fail
  name: underlayvalidationwebhook.openperouter.io
  rules:
  - apiGroups:
    - openpe.openperouter.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - underlays
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: openpe-webhook-service
      namespace: {{ .Release.Namespace | quote }}
      path: /validate-openperouter-io-v1alpha1-l3passthrough
  failurePolicy: Fail
  name: l3passthroughvalidationwebhook.openperouter.io
  rules:
  - apiGroups:
    - openpe.openperouter.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - l3passthroughs
  sideEffects: None
{{- end }}
