// SPDX-License-Identifier:Apache-2.0

package crd

import "embed"

// Manifests contains the generated CRD YAML manifests from config/crd/bases/.
// These are generated by controller-gen from the kubebuilder annotations in api/v1alpha1/.
//
//go:embed bases/*.yaml
var Manifests embed.FS
