#!/bin/bash

if [ -z ${FRR_EDGE+x} ]; then
    source /usr/libexec/frr/frrcommon.sh
    /usr/libexec/frr/watchfrr $(daemon_list)
else
    source /frr-edge/usr/sbin/frrcommon.sh
    /frr-edge/usr/sbin/watchfrr $(daemon_list)
fi
